"""
db/schema_catalog.py
--------------------
Phase 1 — Schema Catalog for the SQL-Generation Agent.

SCHEMA_CATALOG is a structured Python dictionary that describes every
queryable view exposed by the semantic layer. It will be injected into
the SQL-generation agent's system prompt to constrain output to valid
column names and views only.

Usage:
    from db.schema_catalog import SCHEMA_CATALOG
"""

from typing import Dict, List, Any

# ---------------------------------------------------------------------------
# Type alias for readability
# ---------------------------------------------------------------------------
ColumnDef = Dict[str, str]          # {"name": str, "type": str, "description": str}
ViewDef = Dict[str, Any]            # {"description": str, "columns": List[ColumnDef]}
Catalog = Dict[str, ViewDef]

# ---------------------------------------------------------------------------
# Schema Catalog
# ---------------------------------------------------------------------------
SCHEMA_CATALOG: Catalog = {

    # -----------------------------------------------------------------------
    # vw_weekly_sales
    # -----------------------------------------------------------------------
    "vw_weekly_sales": {
        "description": (
            "Weekly sales transactions at the sale-event grain. "
            "Each row represents one sales record for a specific SKU in a given "
            "region and week, optionally linked to an active promotion. "
            "Use this view to answer questions about revenue, units sold, "
            "promotion impact on sales, and regional/category performance."
        ),
        "columns": [
            {
                "name": "sale_id",
                "type": "VARCHAR",
                "description": "Unique identifier for the sales transaction (e.g. SALE00001).",
            },
            {
                "name": "region",
                "type": "VARCHAR",
                "description": "Geographic sales region. Values: North, South, East, West.",
            },
            {
                "name": "week",
                "type": "INTEGER",
                "description": "Week number of the year (1–52).",
            },
            {
                "name": "sku",
                "type": "VARCHAR",
                "description": "Stock-keeping unit identifier (e.g. SKU001–SKU050).",
            },
            {
                "name": "category",
                "type": "VARCHAR",
                "description": (
                    "Product category. Values: Electronics, Groceries, Fashion, Home, Sports."
                ),
            },
            {
                "name": "promo_id",
                "type": "VARCHAR",
                "description": "Foreign key referencing the active promotion (e.g. PROMO001).",
            },
            {
                "name": "units_sold",
                "type": "INTEGER",
                "description": "Number of units sold in this transaction.",
            },
            {
                "name": "revenue",
                "type": "DOUBLE",
                "description": "Total revenue generated by this transaction (units × unit price).",
            },
        ],
    },

    # -----------------------------------------------------------------------
    # vw_weekly_inventory
    # -----------------------------------------------------------------------
    "vw_weekly_inventory": {
        "description": (
            "Weekly inventory snapshots at the region / week / SKU / category grain. "
            "Each row captures the stock level for a specific SKU in a given region "
            "during a specific week. "
            "Use this view to answer questions about stock availability, "
            "inventory movement, and out-of-stock risk."
        ),
        "columns": [
            {
                "name": "inventory_id",
                "type": "VARCHAR",
                "description": "Unique identifier for the inventory snapshot record (e.g. INV00001).",
            },
            {
                "name": "region",
                "type": "VARCHAR",
                "description": "Geographic region where inventory is held. Values: North, South, East, West.",
            },
            {
                "name": "week",
                "type": "INTEGER",
                "description": "Week number of the year (1–52).",
            },
            {
                "name": "sku",
                "type": "VARCHAR",
                "description": "Stock-keeping unit identifier (e.g. SKU001–SKU050).",
            },
            {
                "name": "category",
                "type": "VARCHAR",
                "description": (
                    "Product category. Values: Electronics, Groceries, Fashion, Home, Sports."
                ),
            },
            {
                "name": "stock_level",
                "type": "INTEGER",
                "description": "On-hand inventory quantity for this SKU / region / week combination.",
            },
        ],
    },

    # -----------------------------------------------------------------------
    # vw_promo_calendar
    # -----------------------------------------------------------------------
    "vw_promo_calendar": {
        "description": (
            "Promotion reference calendar — one row per promotion event. "
            "Describes the schedule, scope, and discount depth of each promotion. "
            "Use this view to look up active promotions, filter sales by promotion, "
            "or analyse discount rates across categories and regions."
        ),
        "columns": [
            {
                "name": "promo_id",
                "type": "VARCHAR",
                "description": "Unique promotion identifier (e.g. PROMO001). Primary key.",
            },
            {
                "name": "promo_name",
                "type": "VARCHAR",
                "description": "Human-readable promotion name or campaign title.",
            },
            {
                "name": "region",
                "type": "VARCHAR",
                "description": "Region where the promotion is active. Values: North, South, East, West.",
            },
            {
                "name": "category",
                "type": "VARCHAR",
                "description": (
                    "Product category targeted by the promotion. "
                    "Values: Electronics, Groceries, Fashion, Home, Sports."
                ),
            },
            {
                "name": "start_week",
                "type": "INTEGER",
                "description": "Week number when the promotion starts (1–52, inclusive).",
            },
            {
                "name": "end_week",
                "type": "INTEGER",
                "description": "Week number when the promotion ends (1–52, inclusive).",
            },
            {
                "name": "discount_pct",
                "type": "DOUBLE",
                "description": "Discount percentage offered during the promotion (e.g. 15.5 = 15.5% off).",
            },
        ],
    },
}

# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------

def get_view_names() -> List[str]:
    """Return all queryable view names from the catalog."""
    return list(SCHEMA_CATALOG.keys())


def get_columns(view_name: str) -> List[str]:
    """Return column names for a given view."""
    if view_name not in SCHEMA_CATALOG:
        raise KeyError(f"View '{view_name}' not found in SCHEMA_CATALOG.")
    return [col["name"] for col in SCHEMA_CATALOG[view_name]["columns"]]


def catalog_as_text() -> str:
    """
    Render the full catalog as a human/LLM-readable text block.
    Useful for injecting into a system prompt.
    """
    lines = []
    for view_name, meta in SCHEMA_CATALOG.items():
        lines.append(f"VIEW: {view_name}")
        lines.append(f"  Description: {meta['description']}")
        lines.append("  Columns:")
        for col in meta["columns"]:
            lines.append(
                f"    - {col['name']} ({col['type']}): {col['description']}"
            )
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    print(catalog_as_text())
